version: 1.0.{build}
os: Visual Studio 2015 CTP 6
configuration: Release
platform: Any CPU
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- nuget restore Sources/VKSharp/VKSharp.sln
build:
  parallel: true
  verbosity: minimal